default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: thesis_test_development

test:
  <<: *default
  database: thesis_test_test

production:
  <<: *default
  database: thesis_test_production
  username: thesis_test
  password: <%= ENV['THESIS_TEST_DATABASE_PASSWORD'] %>
